<?
$matriz_elementos = array("Alcalinos (I)"=>array("Li"=>3,
                                                 "Na"=>11,
                                                 "K"=>19,
                                                 "Rb"=>37,
                                                 "Cs"=>55,
                                                 "Fr"=>87),
                        "Alcalino-térreos (II)"=>array("be"=>4,
                                                 "Mg"=>12,
                                                 "Ca"=>20,
                                                 "Sr"=>38,
                                                 "Ba"=>56,
                                                 "Ra"=>88),
                        "Térreos (III)"=>array("Be"=>9,
                                                 "Al"=>5,
                                                 "Ga"=>31,
                                                 "In"=>49,
                                                 "Tl"=>81),
                        "Carbo-noideos"=>array("C"=>"6",
                                                 "Si"=>14,
                                                 "Ge"=>32,
                                                 "Sn"=>50,
                                                 "Pb"=>82),
                        "Nitroge-noideos"=>array("N"=>7,
                                                 "P"=>15,
                                                 "As"=>33,
                                                 "Sb"=>51,
                                                 "Bi"=>83),
                        "Calcógenos-Anfígenos"=>array("O"=>8,
                                                 "S"=>16,
                                                 "Se"=>34,
                                                 "Te"=>52,
                                                 "Po"=>84),
                         "Halógenos"=>array("F"=>9,
                                                 "Cl"=>17,
                                                 "Br"=>35,
                                                 "I"=>53,
                                                 "At"=>85),
                         "Gases Nobles"=>array("He"=>10,
                                                 "Ne"=>18,
                                                 "Ar"=>18,
                                                 "Kr"=>36,
                                                 "Xe"=>54,
                                                 "Rn"=>86));
?>