<?php
$matriz_pilotos = array("Fernando Alonso"=>array("Bharein"=>1,
                                                 "Malasia"=>2,
                                                 "Australia"=>1,
                                                 "S.Marino"=>2,
                                                 "Europa"=>2,
                                                 "España"=>1,
                                                 "Mónaco"=>1),
                        "Michael Schumacher"=>array("Bharein"=>2,
                                                 "Malasia"=>6,
                                                 "Australia"=>"Abandono",
                                                 "S.Marino"=>1,
                                                 "Europa"=>1,
                                                 "España"=>2,
                                                 "Mónaco"=>5),
                        "Felipe Massa"=>array("Bharein"=>9,
                                                 "Malasia"=>5,
                                                 "Australia"=>"Abandono",
                                                 "S.Marino"=>4,
                                                 "Europa"=>3,
                                                 "España"=>4,
                                                 "Mónaco"=>9),
                        "Giancarlo Fisichella"=>array("Bharein"=>"Abandono",
                                                 "Malasia"=>1,
                                                 "Australia"=>5,
                                                 "S.Marino"=>8,
                                                 "Europa"=>6,
                                                 "España"=>3,
                                                 "Mónaco"=>6),
                        "Kimi Raikkonen"=>array("Bharein"=>3,
                                                 "Malasia"=>"Abandono",
                                                 "Australia"=>2,
                                                 "S.Marino"=>5,
                                                 "Europa"=>4,
                                                 "España"=>5,
                                                 "Mónaco"=>"Abandono"),
                        "Jenson Button"=>array("Bharein"=>4,
                                                 "Malasia"=>3,
                                                 "Australia"=>"Abandono",
                                                 "S.Marino"=>7,
                                                 "Europa"=>"Abandono",
                                                 "España"=>6,
                                                 "Mónaco"=>11));
$posiciones = array(1=>10,2=>8,3=>6,4=>5,5=>4,6=>3,7=>2,8=>1,"Abandono"=>0)
?>